apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-react
  labels:
    apps: nginx
spec:
  replicas: 3
  selector: 
    matchLabels:
      apps: nginx
  template:
    metadata:
      labels:
        apps: nginx
    spec:
      containers:
      - name: nginx-react
        image: asia-south1-docker.pkg.dev/awesomeproject-77b88/nginx-react/sre-nginx-test:1
        ports:
        - containerPort: 80
        resources:
          requests: 
            cpu: 150m
            memory: 250Mi
          limits:
            cpu: 500m
            memory: 512Mi