apiVersion: v1
kind: Service
metadata:
  name: nginx-react
  namespace: default
spec:
  type: LoadBalancer
  selector:
    apps: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
